# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
        "name" : "vit_actuary",
        "version" : "0.1",
        "author" : "vitraining",
        "website" : "http://vitraining.com",
        "category" : "Unknown",
        "description": """  """,
        "depends" : ['base'],
        "init_xml" : [ ],
        "demo_xml" : [ ],
        "data" : [
                'views/benefit.xml', 
                'views/product_type.xml', 
                'views/diagnosis.xml', 
                'views/benefit_unit.xml', 
                'views/age_band.xml', 
                'views/membership.xml', 
                'views/existing_insurance.xml', 
                'views/gl_notes.xml', 
                'views/group_size.xml', 
                'views/holiday.xml', 
                'views/lob.xml', 
                'views/membership_factor.xml', 
                'views/modal_factor.xml', 
                'menu.xml',
                'security/ir.model.access.csv',
                # 'data/sequence.xml',
                # 'data/master_data_actuary.xml'
        ],
        "installable": True
}