#!/bin/sh

### BEGIN INIT INFO
# Provides:		odoo
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Should-Start:		$network
# Should-Stop:		$network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Enterprise Resource Management software
# Description:		Open ERP is a complete ERP and CRM software.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
# Di /opt/odoo dicopykan openerp-server > openerp-server8
DAEMON=/opt/odoo/openerp-server8
NAME=openerp-server8
DESC=openerp-server8
CONFIGFILE=/etc/odoo.conf
LOGFILE=/var/log/odoo/odoo.log
#User
USER=odoo2

PIDFILE=/var/run/$NAME.pid
# Additional options that are passed to the Daemon.
DAEMON_OPTS="-c $CONFIGFILE"
# Additional var for start/stop virtualenv
VENV=/opt/odoo2/venv_oddo/bin/

test -x ${DAEMON} || exit 0
[ -f $CONFIGFILE ] || exit 0

checkpid() {
    [ -f $PIDFILE ] || return 1
    pid=`cat $PIDFILE`
    [ -d /proc/$pid ] && return 0
    return 1
}

set -e

do_start () {
    echo -n "Starting ${DESC}: "
    #Aktifkan VENV
    source ${VENV}/activate
    echo -n "Activate ${VENV}"

    # start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid --chuid ${USER} --background --make-pidfile --exec ${DAEMON} -- --config=${CONFIG} --logfile=${LOGFILE}
    start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
		    --chuid ${USER} --background --make-pidfile \
		    --exec ${DAEMON} -- ${DAEMON_OPTS}
    echo "${NAME}."
}

do_stop () {
    echo -n "Stopping ${DESC}: "
    # Deactivate VENV
	source ${VENV}/deactivate
	echo -n "deactivate ${VENV}"

    # start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid --oknodo
    start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
			--oknodo
	echo "${NAME}."
}

case "${1}" in
    start)
        do_start
        ;;

    stop)
        do_stop
        ;;

    restart|force-reload)
        echo -n "Restarting ${DESC}: "
        do_stop
        sleep 1
        do_start
        ;;

    *)
        N=/etc/init.d/${NAME}
        echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
