import partner
import master
import operasional
import spmb
import wisuda
import kelas
import employee
import jadwal
import kurikulum
import invoice
import pembayaran
import reports
import product
import beasiswa
import cuti_kuliah
import partner_calon_mhs
import konversi
import jadwal_usm
import jenis_pendaftaran
import imports
import beasiswa_prodi
import absensi
import users
import ujian
import jadwal_ujian
import krs_by_mhs
import wizard
import partner_registration
import account